LipstickShop/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models.Framework;
using Models.Admin;
using PagedList;
using PagedList.Mvc;
namespace LipstickShop.Controllers
{
    public class CategoriesController : Controller
    {
        private LipstickDbContext db = new LipstickDbContext();

        // GET: Categories
        public async Task<ActionResult> Index(int? page)
        {
            if (page == null) page = 1;
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            var result = await new CategoryModel().Index();
            return View(result.ToPagedList(pageNumber,pageSize));
        }

        // GET: Categories/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var result = await new CategoryModel().Details(id);
            if (result.Id == 0)
            {
                return HttpNotFound();
            }
            return View(result);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Category request)
        {
            if (ModelState.IsValid)
            {
                var result = await new CategoryModel().Create(request);
                if (result > 0)
                {
                    return RedirectToAction("Index");
                }
            }

            return View();
        }

        // GET: Categories/Edit/5
        [HttpGet]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var category = await new CategoryModel().GetEdit(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Category request)
        {
            if (ModelState.IsValid)
            {
                var result = await new CategoryModel().Update(request);
                if (result == 1)
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        // GET: Categories/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = await db.Categories.FindAsync(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Category category = await db.Categories.FindAsync(id);
            db.Categories.Remove(category);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LipstickShop/Controllers/ContactController.cs
using Models.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LipstickShop.Controllers
{
    public class ContactController : Controller
    {
        private LipstickDbContext db = new LipstickDbContext();
        // GET: Contact
        public ActionResult Index()
        {
            var lst = db.Contacts.ToList();
            return View(lst);
        }
    }
}

LipstickShop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models.Framework;

namespace LipstickShop.Controllers
{
    public class ProductsController : Controller
    {
        private LipstickDbContext db = new LipstickDbContext();

        // GET: Products
        public async Task<ActionResult> Index()
        {
            return View(await db.Products.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Alias,CategoryId,Images,Createdate,Price,Detail,Status")] Product product)
        {            
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Alias,CategoryId,Images,Createdate,Price,Detail,Status")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Product product = await db.Products.FindAsync(id);
            db.Products.Remove(product);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LipstickShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="~/Content/css/Dang-nhap.css">
    <link rel="stylesheet" href="~/Content/css/Search.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/Layout.css">

</head>
<body>
    <div class="layout-main">
        <div class="bia-1">
            <div class="logo">
                <a href="./Home_page.html"><img src="~/Content/img/logo.jpg"></a>
            </div>
        </div>
        <div class="bia-2">
            <div class="logo-2">
                <a href="#"><img onclick="openSearch()" src="~/Content/img/seach.jpg"></a>
                <!-- div script search -->
                <div id="myOverlay" class="overlay">
                    <span class="closebtn" onclick="closeSearch()" title="Close Overlay">×</span>
                    <div class="overlay-content">
                        <form action>
                            <input type="text" placeholder="Search.." name="search">
                            <button type="submit" style="width: 110px;height: 50px;">SEACH</button>
                        </form>
                    </div>
                </div>
                <script language="javascript" src="~/Content/js/Search.js"></script>
                <!--  -->
                
                
                <a href="./Dang-nhap.html"><img src="~/Content/img/nguoi.jpg"></a>
                
                <a href="./Your-cart.html"><img src="~/Content/img/gio.jpg"></a>
            </div>
        </div>
    </div>

    <div id="menu">
        <ul>
            <li>
                <a href="#"> SHOP ACCESSORIS</a>
                <ul class="sub-menu">
                    <li><a href="#"> VIEW ALL</a></li>
                    <li><a href="#"> SCARVES</a></li>
                    <li><a href="#"> HANDBAGS</a></li>
                </ul>
            </li>

            <li>
                <a href="#"> SHOP BOTTOMS</a>
                <ul class="sub-menu">
                    <li><a href="#"> VIEW ALL</a></li>
                    <li><a href="#"> BOTTOMS</a></li>
                    <li><a href="#"> JEANS</a></li>
                </ul>
            </li>

            <li>
                <a href="#"> SHOP CLOTHING</a>
                <ul class="sub-menu">
                    <li><a href="#"> VIEW ALL</a></li>
                    <li><a href="#"> SWEATERS</a></li>
                    <li><a href="#"> T-SHIRTS</a></li>
                </ul>
            </li>

            <li>
                <a href="#"> SHOP FOOTWEAR</a>
                <ul class="sub-menu">
                    <li><a href="#"> VIEW ALL</a></li>
                    <li><a href="#"> CROCS</a></li>
                    <li><a href="#"> HEELS</a></li>
                </ul>
            </li>
        </ul>
    </div>

    <!-- THIS THING -->
    @RenderBody();


    <!-- THIS THING -->
    <div class="layout-3">
        <div class="layout-3-1">
            <h1 class="h1-cuoi">Quick links</h1>

            <h5 class="h5-cuoi">
                <a class="link" href="./The-new.html">The News</a><br>
                <a class="link" href="./Map.html">Visit Our Stores</a><br>
                <a class="link" href="#">Seach</a><br>
                <a class="link" href="#">FAQs</a><br>
                <a class="link" href="#">Return & Refunds</a>
            </h5>
        </div>

        <div class="layout-3-2">
            <h1 class="h1-cuoi">Subscribe To Our Mailing List!</h1><br>
            <form action="#" method="get">
                <input class="tim-kiem" type="text" name="" placeholder="Email address">
            </form>

            <div class="dangky">
                <a href="#"><h3 class="h3-cuoi">SUBSCRIBE</h3></a>
            </div>
        </div>

        <div class="layout-3-3">
            <h1 class="h1-cuoi">Lipstick Clothing Ireland</h1>
            <h5 class="h5-cuoi">Contact <br> quannm2812@gmail.com</h5>
        </div>
    </div>

    <div class="footer">
        <div class="last_footer">
            <ul>
                <img src="~/Content/img/img_mastercard.jpg">
                <img src="~/Content/img/img_visa.jpg">
            </ul>
            <ul class="fb_insta">
                <img src="~/Content/img/img_fb.jpg">
                <img src="~/Content/img/img_instagram.jpg">
            </ul>
        </div>
    </div>
</body>
</html>

LipstickShop/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/Content/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">ADMIN</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="/Profile/Index">@User.Identity.Name</a></li>
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li>@Html.ActionLink("DangXuat", "Logout", "AdminLogin", null, new { @class = "dropdown-item" })</li>

                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Chỉnh sửa chính
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                @Html.ActionLink("Sản phẩm", "Index", "Products", null, new { @class = "nav-link" })
                                @Html.ActionLink("Loại sản phẩm", "Index", "Categories", null, new { @class = "nav-link" })
                                @Html.ActionLink("Liên hệ", "Index", "Contact", null, new { @class = "nav-link" })
                                @*<a class="nav-link" href="layout-sidenav-light.html">Người Dùng</a>*@
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Login</a>
                                        <a class="nav-link" href="register.html">Register</a>
                                        <a class="nav-link" href="password.html">Forgot Password</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="401.html">401 Page</a>
                                        <a class="nav-link" href="404.html">404 Page</a>
                                        <a class="nav-link" href="500.html">500 Page</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tables
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2021</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/chart-area-demo.js"></script>
    <script src="assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="js/datatables-simple-demo.js"></script>
</body>
</html>