IUseLipstickShop/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models.Framework;
using PagedList;
using PagedList.Mvc;
using Models;
using Models.User;

namespace IUseLipstickShop.Controllers
{
    public class EventsController : Controller
    {
        private LipstickDbContext db = new LipstickDbContext();

        // GET: Events
        public async Task<ActionResult> Index(int? page)
        {
            if (page == null) page = 1;
            int pageSize = 12;
            int pageNumber = (page ?? 1);
            
            var result = await db.Products.ToListAsync();
            return View((result.ToPagedList(pageNumber, pageSize)));
        }

        // GET: Events/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            SetViewBag();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.Products.FindAsync(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        public void SetViewBag(int? selectedId = null)
        {
            
            var dao = new EventsModels(); 
            ViewBag.Colour = new SelectList(dao.ListAll(),"Id","colour1", selectedId);
            ViewBag.Size = new SelectList(dao.ListAllSize(), "Id", "C_size", selectedId);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

IUseLipstickShop/Controllers/HomeController.cs
using Models.Framework;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IUseLipstickShop.Controllers
{
    public class HomeController : Controller
    {
        private LipstickDbContext db = new LipstickDbContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductsJK(int? page)
        {
            if (page == null) page = 1;
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            var lst = db.Products.Where(x => x.Alias == "ao-khoac").ToList();
            return PartialView((lst.ToPagedList(pageNumber, pageSize)));
        }

        public ActionResult ProductsHD(int? page)
        {
            if (page == null) page = 1;
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            var lst = db.Products.Where(x => x.Alias == "hoodie").ToList();
            return PartialView((lst.ToPagedList(pageNumber, pageSize)));
        }
        public ActionResult ProductsJ(int? page)
        {
            if (page == null) page = 1;
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            var lst = db.Products.Where(x => x.Alias == "jean").ToList();
            return PartialView((lst.ToPagedList(pageNumber, pageSize)));
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        [ChildActionOnly]
        public ActionResult RenderMenu(int? id)
        {
            var result = db.Categories.ToList();
            return PartialView("MenuBar");
        }
        public ActionResult Search(string TenSP)
        {
            if (TenSP == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var lst = db.Products.Where(x => x.Name.Contains(TenSP)).ToList();
            return View(lst);
        }

    }
}

IUseLipstickShop/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

IUseLipstickShop/Views/Home/Index.cshtml
@model PagedList.IPagedList<Models.Framework.Product>
@using PagedList.Mvc;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link rel="stylesheet" type="text/css" href="~/Content/css/Home_page.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/Slide_show.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/Trang-chu.css">
    <title>Lipstick Clothing</title>

</head>

<div class="banner_1">
    <!-- 			 -->
    <div class="slideshow-container">
        <div class="mySlides fade">
            <div class="numbertext"></div>
            <img src="~/Content/img/banner3.jpg" width="100%">
        </div>
        <div class="mySlides fade">
            <div class="numbertext"></div>
            <img src="~/Content/img/banner1.jpg" width="100%">
        </div>
        <div class="mySlides fade">
            <div class="numbertext"></div>
            <img src="~/Content/img/banner2.jpg" width="100%">
        </div>
        <div class="mySlides fade">
            <div class="numbertext"></div>
            <img src="~/Content/img/banner1.jpg" width="100%">
        </div>
        <!-- Nút điều khiển mũi tên-->
        <a class="prev" onclick="plusSlides(-1)">❮</a>
        <a class="next" onclick="plusSlides(1)">❯</a>
    </div>
    <br>
    <div style="text-align:center">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
        <span class="dot" onclick="currentSlide(4)"></span>
    </div>
    <script language="javascript" src="~/Content/js/banner_slideshow.js"></script>
</div>


@Html.Action("ProductsJK", "Home")
@Html.Action("ProductsHD", "Home")
@Html.Action("ProductsJ", "Home")

<div class="banner_2">
    <img src="~/Content/img/banner2.jpg" width="100%">
</div>

<br />
<div class="blog" style="width: 100%; height: 600px">
    <div class="row" style="width: 70%; height: 50px; margin: 0 auto;">
        <p style="text-align: center; font-size: 26px; font-weight: 200; font-family: 'Quattrocento Sans', sans-serif; line-height: 1.80857;">Latest Blogs</p>
    </div>
    <div class="row" style="width: 70%; height: 550px; margin: 0 auto;display:flex">
        <div style="width: 33.33%;padding: 20px;">
            <img src="~/Content/img/blog-img.jpg" width="100%" />
            <h3 style="text-align: center; padding: 10px; font-family: 'Quattrocento Sans', sans-serif; line-height: 1.80857;">Fusce in augue non nisi fringilla</h3>
            <div style="display:flex">
                <div class="option-blog">
                    <div style="width: 34px; height: 34px; align-items: center;">
                        <a href="#" data-toggle="tooltip" data-placement="right" title="Likes"><img src="~/Content/img/heart.svg" /></a>
                    </div>
                    <div style="width:34px; height:34px;">
                        <a href="#" data-toggle="tooltip" data-placement="right" title="Views"><img src="~/Content/img/eye.svg" /></a>
                    </div>
                    <div style="width:34px; height:34px;">
                        <a href="#" data-toggle="tooltip" data-placement="right" title="Comments"><img src="~/Content/img/chat-right-text.svg" /></a>
                    </div>
                </div>
                <p style="color: #666666; font-size: 15px; font-family: 'Quattrocento Sans', sans-serif; line-height: 1.80857;">Nulla ut urna egestas, porta libero id, suscipit orci. Quisque in lectus sit amet urna dignissim feugiat. Mauris molestie egestas pharetra. Ut finibus cursus nunc sed mollis. Praesent laoreet lacinia elit id lobortis.</p>
            </div>
        </div>
        <div style="width: 33.33%;padding: 20px;">
            <img src="~/Content/img/blog-img-01.jpg" width="100%" />
            <h3 style="text-align: center; padding: 10px; font-family: 'Quattrocento Sans', sans-serif; line-height: 1.80857;">Fusce in augue non nisi fringilla</h3>
            <div style="display:flex">
                <div class="option-blog">
                    <div style="width: 34px; height: 34px; align-items: center;">
                        <a href="#" data-toggle="tooltip" data-placement="right" title="Likes"><img src="~/Content/img/heart.svg" /></a>
                    </div>
                    <div style="width:34px; height:34px;">
                        <a href="#" data-toggle="tooltip" data-placement="right" title="Views"><img src="~/Content/img/eye.svg" /></a>
                    </div>
                    <div style="width:34px; height:34px;">
                        <a href="#" data-toggle="tooltip" data-placement="right" title="Comments"><img src="~/Content/img/chat-right-text.svg" /></a>
                    </div>
                </div>
                <p style="color: #666666; font-size: 15px; font-family: 'Quattrocento Sans', sans-serif; line-height: 1.80857;">Nulla ut urna egestas, porta libero id, suscipit orci. Quisque in lectus sit amet urna dignissim feugiat. Mauris molestie egestas pharetra. Ut finibus cursus nunc sed mollis. Praesent laoreet lacinia elit id lobortis.</p>
            </div>
        </div>
        <div style="width: 33.33%;padding: 20px;">
            <img src="~/Content/img/blog-img-02.jpg" width="100%" />
            <h3 style="text-align: center; padding: 10px; font-family: 'Quattrocento Sans', sans-serif; line-height: 1.80857;">Fusce in augue non nisi fringilla</h3>
            <div style="display:flex">
                <div class="option-blog">
                    <div style="width: 34px; height: 34px; align-items: center;">
                        <a href="#" data-toggle="tooltip" data-placement="right" title="Likes"><img src="~/Content/img/heart.svg" /></a>
                    </div>
                    <div style="width:34px; height:34px;">
                        <a href="#" data-toggle="tooltip" data-placement="right" title="Views"><img src="~/Content/img/eye.svg" /></a>
                    </div>
                    <div style="width:34px; height:34px;">
                        <a href="#" data-toggle="tooltip" data-placement="right" title="Comments"><img src="~/Content/img/chat-right-text.svg" /></a>
                    </div>
                </div>
                <p style="color: #666666; font-size: 15px; font-family: 'Quattrocento Sans', sans-serif; line-height: 1.80857;">Nulla ut urna egestas, porta libero id, suscipit orci. Quisque in lectus sit amet urna dignissim feugiat. Mauris molestie egestas pharetra. Ut finibus cursus nunc sed mollis. Praesent laoreet lacinia elit id lobortis.</p>
            </div>
        </div>
    </div>
</div>

<br />
<hr />
<div style="width: 30%; margin:0 auto;border: 1px solid #000000">

</div>
<div class="about_us">
    <p align="center">Follow us on Facebook!</p>
    <p align="center">Join the community on our Facebook channel</p>
    <p align="center">lipstick clothes to get news on upcoming</p>
    <p align="center">online and in-store promotions, unique</p>
    <p align="center">facebook offers and much more!</p>
</div>

<br /><br />

IUseLipstickShop/Views/Home/ProductsHD.cshtml
@model PagedList.IPagedList<Models.Framework.Product>
@using PagedList.Mvc;
<br />
<br />


<div style="height: 500px; background-color: #fff">
    <div style="width: 70%; height:30px; margin: 0 auto; border-bottom: 1px #30636b solid;">
        <span style="font-size:24px;">HOODIE</span>
    </div>
    <div class="view" style="width:80%; margin: 0 auto;">
        <ul style="margin-left: 155px;">
            @foreach (var item in Model)
            {
                <li>
                    <div class="scarves">
                        <a type="submit" class="hover"
                           href="@Url.Action("Details", "Events", new { id = item.Id })">
                            <img style="height:300px" src="~/Content/img/@Html.DisplayFor(modelItem => item.Images)">
                            <h3 class="h3-main"> @Html.DisplayFor(modelItem => item.Name)</h3>
                        </a>
                        <img style="float: left; margin-left: 5px" src="~/Content/img/new.jpg" width="50px">
                        <b><p style="float: left; margin-left: 5px ">€ @Html.DisplayFor(modelItem => item.Price)</p></b>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

IUseLipstickShop/Views/Home/ProductsJ.cshtml
@model PagedList.IPagedList<Models.Framework.Product>
@using PagedList.Mvc;
<br />
<br />


<div style="height: 500px; background-color: #fff">
    <div style="width: 70%; height:30px; margin: 0 auto; border-bottom: 1px #30636b solid;">
        <span style="font-size:24px;">JEAN</span>
    </div>
    <div class="view" style="width:80%; margin: 0 auto;">
        <ul style="margin-left: 155px;">
            @foreach (var item in Model)
            {
                <li>
                    <div class="scarves">
                        <a type="submit" class="hover"
                           href="@Url.Action("Details", "Events", new { id = item.Id })">
                            <img style="height:300px" src="~/Content/img/@Html.DisplayFor(modelItem => item.Images)">
                            <h3 class="h3-main"> @Html.DisplayFor(modelItem => item.Name)</h3>
                        </a>
                        <img style="float: left; margin-left: 5px" src="~/Content/img/new.jpg" width="50px">
                        <b><p style="float: left; margin-left: 5px ">€ @Html.DisplayFor(modelItem => item.Price)</p></b>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

IUseLipstickShop/Views/Home/ProductsJK.cshtml
@model PagedList.IPagedList<Models.Framework.Product>
@using PagedList.Mvc;
<br />
<br />


<div style="height: 500px; background-color: #fff">
    <div style="width: 70%; height:30px; margin: 0 auto; border-bottom: 1px #30636b solid;">
        <span style="font-size:24px;">JACKET</span>
    </div>
    <div class="view" style="width:80%; margin: 0 auto;">
        <ul style="margin-left: 155px;">
            @foreach (var item in Model)
            {
                <li>
                    <div class="scarves">
                        <a type="submit" class="hover"
                           href="@Url.Action("Details", "Events", new { id = item.Id })">
                            <img style="height:300px" src="~/Content/img/@Html.DisplayFor(modelItem => item.Images)">
                            <h3 class="h3-main"> @Html.DisplayFor(modelItem => item.Name)</h3>
                        </a>
                        <img style="float: left; margin-left: 5px" src="~/Content/img/new.jpg" width="50px">
                        <b><p style="float: left; margin-left: 5px ">€ @Html.DisplayFor(modelItem => item.Price)</p></b>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

IUseLipstickShop/Views/Home/Search.cshtml
@model IEnumerable<Models.Framework.Product>
@{ 
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}
<head>
    <link rel="stylesheet" type="text/css" href="~/Content/css/Trang-chu.css">
</head>
<!-- THIS THING -->
<br />
<div style="width: 80%; margin: auto">
    <h3 style="background: #ff7675; width: fit-content; border-radius: 10px; padding: 5px;">Đã tìm thấy @Model.Count() sản phẩm</h3>
</div>

<div style="height: auto; background-color: #ffcccc">
    <div class="main" style="width:70%; margin: auto;">
        <div class="view">
            <ul>
                @foreach (var item in Model)
                {
                    <li style=" border:1px solid;border-radius:20px; z-index: 0">
                        <div class="scarves">
                            <a type="submit" class="hover"
                               href="@Url.Action("Details", "Events", new { id = item.Id })">
                                <img style="height:300px" src="~/Content/img/@Html.DisplayFor(modelItem => item.Images)">
                                <h3 class="h3-main"> @Html.DisplayFor(modelItem => item.Name)</h3>
                            </a>
                            <img style="float: left; margin-left: 5px" src="~/Content/img/new.jpg" width="50px">
                            <b><p style="float: left; margin-left: 5px ">€ @Html.DisplayFor(modelItem => item.Price)</p></b>
                        </div>
                    </li>
                 }
            </ul>
        </div>
    </div>
</div>